### ISSUE TITLE
Support C++98

### ISSUE THREAD

**Issue by FastInvite2k2** [omartijn/cpprouter#13]

**Comment by omartijn** [comment]
Unfortunately, I don't see a realistic way to do this without severely compromising the API of this library.

C++98 does not support `auto` template parameters, which are used to register the callbacks. This _could_ be done by adding another template parameter, which would get the `decltype` of the callback to register (which is ugly in itself, but still within reason).

The larger problem is the lack of support for variadic templates, which means that it's not possible to template the library on a specific callback type (because I don't know the number of template parameters in advance), and which also eliminates the option for forwarding parameters to the callback as well as deducing the callback type and which slug parameters it gets.

So unfortunately, this is not a request I feel I can fulfill. Perhaps you can tell me why exactly you are asking for this? What are you trying to achieve, exactly, and on what arcane platform are you working that you have to use a 22-year old C++-version.
